[aliases]
test=pytest

[tool:pytest]
addopts = --pylint --pylint-rcfile=./pylintrc --cov=mlidea --cov-report=xml
# Maybe we need to skip stdout capturing at some point if we add tests that test
#  functionality that relies on it

[metadata]
name = mlidea
version = 0.0.1.dev26
author = Stefan Grafberger
author_email = stefangrafberger@gmail.com
description = Interactively Improving ML Data Preparation Code via Shadow Pipelines
long_description = file: README.md
long_description_content_type = text/markdown
license = Apache License 2.0
classifiers =
    License :: OSI Approved :: Apache Software License
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.11

[options]
include_package_data = True
install_requires = file: requirements.txt
python_requires = >=3.10,<3.12
packages = find:
